<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            [
                'name' => 'Chirurgia tkanek miękkich',
                'slug' => 'chirurgia-tkanek-miekkich',
                'description' => '<strong>"Chirurgia tkanek miękkich"</strong> to specjalizacja zajmująca się diagnozowaniem i leczeniem schorzeń oraz urazów związanych z miękkimi tkankami zwierząt, do których zaliczają się mięśnie, skóra, narządy wewnętrzne, naczynia krwionośne, więzadła i ścięgna. Proces ten rozpoczyna się od diagnostyki, w której weterynarz przeprowadza szczegółowe badania, takie jak obrazowe (RTG, USG) i badania krwi, aby ocenić stan zdrowia zwierzęcia i określić potrzebę operacji. Przygotowanie do zabiegu obejmuje ocenę ryzyka związanego ze znieczuleniem, przygotowanie pola operacyjnego, w tym ogolenie odpowiedniego obszaru ciała, oraz wprowadzenie zwierzęcia w znieczulenie ogólne. Chirurgia tkanek miękkich obejmuje szeroki zakres zabiegów, w tym usuwanie guzów, operacje na narządach wewnętrznych takich jak żołądek, jelita, wątroba, śledziona czy pęcherz moczowy, zabiegi na układzie rozrodczym, takie jak sterylizacja, kastracja i cesarskie cięcie, naprawa przepuklin, a także leczenie ran, które nie goją się samodzielnie. Po operacji weterynarz monitoruje stan zwierzęcia, podaje leki przeciwbólowe i antybiotyki oraz udziela właścicielowi wskazówek dotyczących opieki w czasie rekonwalescencji. Głównym celem chirurgii tkanek miękkich jest poprawa jakości życia zwierzęcia poprzez usunięcie lub naprawienie uszkodzonych tkanek, leczenie chorób oraz zapobieganie dalszym komplikacjom zdrowotnym. Dzięki temu zwierzę może wrócić do zdrowia i pełnej sprawności. Chirurgia tkanek miękkich jest kluczowym elementem opieki weterynaryjnej, umożliwiającym leczenie wielu poważnych schorzeń, które znacząco wpływają na komfort życia i długowieczność zwierząt.',
                'price' => 80,
            ],
            [
                'name' => 'Dermatologia',
                'slug' => 'dermatologia',
                'description' => '<strong>"Dermatologia"</strong> w weterynarii to dziedzina zajmująca się głównie diagnozowaniem oraz leczeniem schorzeń skóry oraz związanych z nią struktur, takich jak sierść, pazury, gruczoły łojowe i potowe. Proces leczenia w dermatologii weterynaryjnej rozpoczyna się od szczegółowej diagnostyki, która może obejmować badania kliniczne, testy alergiczne, badania mikroskopowe próbek skóry oraz biopsje, mające na celu ustalenie przyczyny problemu skórnego. Weterynarz dokładnie ocenia stan skóry zwierzęcia, analizując zmiany skórne, obecność świądu, łuszczenia się, wysięków czy zaczerwienień. W zależności jakie są wyniki diagnozy, lekarz weterynarii może zalecić odpowiednie leczenie, które często obejmuje stosowanie miejscowych lub ogólnoustrojowych leków, takich jak maści, kremy, szampony lecznicze, antybiotyki, leki przeciwgrzybicze lub przeciwzapalne. W przypadkach alergii, istotnym elementem terapii jest identyfikacja i eliminacja alergenów, co może wymagać zmiany diety, unikania określonych substancji lub stosowania immunoterapii. Weterynarz może również zalecić suplementy wspomagające zdrowie skóry, takie jak kwasy tłuszczowe omega-3 i omega-6. Po wdrożeniu leczenia, weterynarz monitoruje postępy w gojeniu się skóry i reaguje na ewentualne nawroty problemu. Celem dermatologii weterynaryjnej jest przywrócenie zdrowia skóry zwierzęcia, zmniejszenie dyskomfortu związanego między innymi z chorobami dermatologicznymi oraz poprawa ogólnego samopoczucia i jakości życia zwierzęcia. Dermatologia jest niezbędnym elementem opieki weterynaryjnej, ponieważ zdrowa skóra odgrywa kluczową rolę w ochronie organizmu przed infekcjami, utrzymaniu właściwej termoregulacji oraz zapewnieniu komfortu życia zwierząt.',
                'price' => 110,
            ],
            [
                'name' => 'EKG',
                'slug' => 'ekg',
                'description' => '<strong>"EKG"</strong> to procedura diagnostyczna polegająca na rejestrowaniu elektrycznej aktywności serca zwierzęcia, co pozwala na ocenę jego funkcjonowania i wykrycie ewentualnych nieprawidłowości. Badanie EKG jest szczególnie istotne w diagnozowaniu zaburzeń rytmu serca, arytmii, a także w ocenie skutków chorób sercowo-naczyniowych, które mogą wpływać na zdrowie zwierzęcia. Procedura ta rozpoczyna się od przygotowania zwierzęcia, które obejmuje umieszczenie elektrod na ciele w odpowiednich miejscach, zazwyczaj na kończynach i klatce piersiowej, aby uzyskać dokładne odczyty. Elektrokardiogram rejestruje zmiany potencjału elektrycznego serca w trakcie jego pracy, a wyniki są przedstawiane w postaci charakterystycznych fal i odcinków, które weterynarz analizuje pod kątem nieprawidłowości. Interpretacja wyników EKG pozwala na ocenę rytmu serca, identyfikację obecności arytmii, ocenę wielkości komór serca oraz wykrycie objawów niewydolności serca. W przypadku stwierdzenia nieprawidłowości, weterynarz może zalecić dodatkowe badania, takie jak echokardiografia czy badania krwi, aby uzyskać pełniejszy obraz stanu zdrowia serca. EKG jest również używane do monitorowania skuteczności leczenia chorób sercowych, zwłaszcza w przypadku stosowania leków regulujących rytm serca lub obniżających ciśnienie krwi. Dzięki regularnym badaniom EKG można wczesniej wykryć problemy sercowe i rozpocząć odpowiednie leczenie, co jest kluczowe dla poprawy jakości życia i przedłużenia życia zwierzęcia. Badanie EKG w weterynarii jest niezbędnym narzędziem diagnostycznym, które pozwala na skuteczne zarządzanie zdrowiem serca zwierząt, zapewniając im odpowiednią opiekę i monitorowanie w przypadkach chorób sercowo-naczyniowych.',
                'price' => 120,
            ],
            [
                'name' => 'Fryzjerstwo',
                'slug' => 'fryzjerstwo',
                'description' => '<strong>"Fryzjerstwo"</strong> w weterynarii, znane również jako grooming, to specjalistyczna usługa polegająca na pielęgnacji sierści, skóry oraz pazurów zwierząt. Celem fryzjerstwa weterynaryjnego jest nie tylko poprawa wyglądu zwierzęcia, ale przede wszystkim zapewnienie mu zdrowia i komfortu. Proces ten rozpoczyna się od dokładnego wyczesania sierści, co pomaga usunąć martwe włosy, zanieczyszczenia oraz zapobiega powstawaniu kołtunów, które mogą powodować dyskomfort, a nawet ból u zwierzęcia. W zależności od potrzeb, fryzjer może również przyciąć sierść, nadając jej odpowiedni kształt i długość, co jest szczególnie ważne w przypadku ras wymagających regularnej pielęgnacji. Oprócz strzyżenia, grooming obejmuje także pielęgnację skóry, kąpiel przy użyciu specjalistycznych szamponów oraz odżywek, które pomagają utrzymać skórę w dobrej kondycji i zapobiegają problemom dermatologicznym. Dbanie o higienę uszu, oczu oraz przycinanie pazurów to kolejne istotne elementy fryzjerstwa weterynaryjnego, które zapobiegają infekcjom, podrażnieniom oraz urazom. Regularne wizyty u fryzjera weterynaryjnego mają również aspekt profilaktyczny, ponieważ podczas pielęgnacji można wcześnie wykryć różne problemy zdrowotne, takie jak zmiany skórne, pasożyty czy infekcje, co pozwala na szybką reakcję i leczenie. Fryzjerstwo weterynaryjne jest zatem nie tylko kwestią estetyki, ale przede wszystkim zdrowia i dobrostanu zwierzęcia. Dzięki regularnej pielęgnacji, zwierzęta czują się bardziej komfortowo, są chronione przed infekcjami skórnymi, a ich sierść jest zdrowa i lśniąca. W kontekście opieki weterynaryjnej, fryzjerstwo odgrywa ważną rolę w zapewnieniu zwierzęciu odpowiedniej opieki, która wpływa na jego ogólne samopoczucie i jakość życia.',
                'price' => 30,
            ],
            [
                'name' => 'Ortopedia',
                'slug' => 'ortopedia',
                'description' => '<strong>"Ortopedia"</strong> to dziedzina zajmująca się diagnozowaniem, leczeniem i zapobieganiem schorzeniom oraz urazom układu kostno-stawowego i mięśniowego u zwierząt. Specjalizacja ta obejmuje szeroki zakres problemów, w tym złamania kości, zwichnięcia, choroby stawów, takie jak artretyzm, dysplazja stawów biodrowych, a także wady postawy i problemy związane z układem ruchu. Proces leczenia w ortopedii weterynaryjnej rozpoczyna się od szczegółowej diagnostyki, która może obejmować badania obrazowe, takie jak rentgen, tomografia komputerowa czy rezonans magnetyczny, a także badania kliniczne, mające na celu ocenę stanu kości, stawów i mięśni. W zależności od rodzaju i stopnia zaawansowania schorzenia, weterynarz może zalecić różne metody leczenia, w tym zarówno konserwatywne, jak i chirurgiczne. Konserwatywne metody obejmują rehabilitację, fizjoterapię, podawanie leków przeciwzapalnych, przeciwbólowych oraz suplementów wspomagających zdrowie stawów. W przypadkach poważniejszych urazów lub chorób, może być konieczne przeprowadzenie operacji, takich jak stabilizacja złamań za pomocą implantów, rekonstrukcja więzadeł, artroskopia czy wymiana stawu. Po operacji niezwykle ważna jest rehabilitacja, która pomaga zwierzęciu wrócić do pełnej sprawności ruchowej. Celem ortopedii weterynaryjnej jest nie tylko przywrócenie zwierzęciu możliwości normalnego funkcjonowania, ale także poprawa jego jakości życia poprzez redukcję bólu, poprawę mobilności oraz zapobieganie dalszym komplikacjom zdrowotnym. Ortopedia odgrywa kluczową rolę w opiece nad zwierzętami, szczególnie tymi, które cierpią na przewlekłe schorzenia układu ruchu, ponieważ odpowiednia diagnostyka i leczenie mogą znacząco wpłynąć na ich komfort i długość życia.',
                'price' => 60,
            ],
            [
                'name' => 'Sterylizacja i kastracja',
                'slug' => 'sterylizacja-i-kastracja',
                'description' => '<strong>"Sterylizacja i kastracja"</strong> to powszechne zabiegi chirurgiczne mające na celu kontrolę rozrodu zwierząt oraz poprawę ich zdrowia i jakości życia. Sterylizacja, dotycząca głównie samic, polega na usunięciu jajników, a często także macicy, co zapobiega ciąży i eliminuje cykl rujowy. Kastracja, stosowana u samców, polega na usunięciu jąder, co również zapobiega rozmnażaniu oraz zmniejsza poziom hormonów płciowych, wpływających na zachowanie zwierzęcia. Przed przystąpieniem do zabiegu, weterynarz przeprowadza dokładną ocenę stanu zdrowia zwierzęcia, w tym badania krwi i inne niezbędne testy, aby upewnić się, że operacja jest bezpieczna. Sam zabieg jest przeprowadzany w znieczuleniu ogólnym, a po jego zakończeniu zwierzę otrzymuje odpowiednie leki przeciwbólowe oraz antybiotyki w celu zapobiegania infekcjom. Proces rekonwalescencji jest zazwyczaj krótki, a weterynarz dostarcza właścicielowi szczegółowe instrukcje dotyczące opieki pooperacyjnej, takie jak ograniczenie aktywności fizycznej zwierzęcia oraz monitorowanie rany operacyjnej. Sterylizacja i kastracja mają wiele korzyści zdrowotnych. U samic zabieg ten znacząco redukuje ryzyko rozwoju nowotworów sutka oraz zapalenia macicy, które mogą być groźne dla życia. U samców kastracja zmniejsza ryzyko wystąpienia nowotworów jąder oraz schorzeń prostaty, a także może łagodzić agresywne zachowania i tendencje do ucieczek. Oprócz korzyści zdrowotnych, sterylizacja i kastracja są także ważnymi elementami kontroli populacji zwierząt, zapobiegając nadmiernemu rozrodowi, który często prowadzi do bezdomności zwierząt. W kontekście opieki weterynaryjnej, sterylizacja i kastracja to zabiegi, które nie tylko chronią zdrowie zwierząt, ale także wspierają odpowiedzialne podejście do posiadania zwierząt, przyczyniając się do zmniejszenia liczby niechcianych miotów oraz poprawy jakości życia zarówno zwierząt, jak i ich opiekunów.',
                'price' => 65,
            ],
            [
                'name' => 'Okulistyka',
                'slug' => 'okulistyka',
                'description' => '<strong>"Okulistyka"</strong> to specjalizacja zajmująca się diagnozowaniem i leczeniem schorzeń oraz urazów oczu u zwierząt. Dziedzina ta obejmuje szeroki zakres problemów, takich jak infekcje oczu, zapalenie spojówek, zaćma, jaskra, wrzody rogówki, a także wrodzone i nabyte wady wzroku. Proces diagnostyczny w weterynaryjnej okulistyce rozpoczyna się od szczegółowego badania oczu, które może obejmować testy widzenia, badanie ciśnienia wewnątrzgałkowego, fluoresceinowy test barwienia rogówki oraz użycie specjalistycznych narzędzi, takich jak oftalmoskop czy biomikroskop. Po postawieniu diagnozy weterynarz opracowuje plan leczenia dostosowany do indywidualnych potrzeb zwierzęcia. W zależności od rodzaju schorzenia, leczenie może obejmować podawanie leków w postaci kropli do oczu, maści, a także leków ogólnoustrojowych, takich jak antybiotyki czy środki przeciwzapalne. W poważniejszych przypadkach, takich jak zaawansowana zaćma czy wrzody rogówki, może być konieczne przeprowadzenie operacji. Zabiegi okulistyczne w weterynarii, takie jak usunięcie zaćmy, rekonstrukcja rogówki czy operacje korekcyjne powiek, wymagają precyzji i specjalistycznej wiedzy, aby przywrócić lub poprawić funkcje wzroku zwierzęcia. Okulistyka weterynaryjna odgrywa kluczową rolę w zachowaniu jakości życia zwierząt, ponieważ problemy ze wzrokiem mogą znacząco wpływać na ich codzienne funkcjonowanie i komfort. Wczesne wykrycie i leczenie schorzeń okulistycznych pozwala nie tylko na zachowanie wzroku, ale także na zapobieganie powikłaniom, które mogą prowadzić do utraty widzenia lub przewlekłego bólu. Regularne badania okulistyczne są szczególnie ważne dla zwierząt starszych oraz tych, które mają predyspozycje genetyczne do chorób oczu. W ramach kompleksowej opieki weterynaryjnej, okulistyka jest niezwykle istotnym elementem, który pomaga zapewnić zwierzętom pełne i zdrowe życie, poprzez skuteczną diagnostykę, leczenie i monitorowanie zdrowia ich oczu.',
                'price' => 80,
            ],
            [
                'name' => 'Stomatologia',
                'slug' => 'stomatologia',
                'description' => '<strong>"Stomatologia"</strong> w weterynarii to specjalizacja zajmująca się diagnozowaniem, leczeniem i profilaktyką chorób jamy ustnej, zębów oraz przyzębia u zwierząt. Problemy stomatologiczne są często spotykane, a ich zaniedbanie może prowadzić do poważnych komplikacji zdrowotnych, w tym infekcji, utraty zębów, a nawet ogólnoustrojowych schorzeń związanych z przenikaniem bakterii z jamy ustnej do krwiobiegu. Stomatologia weterynaryjna obejmuje szeroki zakres usług, takich jak usuwanie kamienia nazębnego, leczenie zapalenia dziąseł, ekstrakcje zębów, leczenie złamań zębów, a także korekcję wad zgryzu. Proces opieki stomatologicznej rozpoczyna się od dokładnego badania jamy ustnej zwierzęcia. Weterynarz ocenia stan zębów, dziąseł oraz całej jamy ustnej, poszukując oznak chorób, takich jak płytka nazębna, kamień, krwawienie dziąseł, ubytki czy nieprzyjemny zapach z pyska, który może wskazywać na poważniejsze problemy. W zależności od stanu zdrowia jamy ustnej, weterynarz może zalecić różne zabiegi, w tym profesjonalne czyszczenie zębów w znieczuleniu ogólnym, co pozwala na dokładne usunięcie kamienia nazębnego zarówno z powierzchni zębów, jak i spod linii dziąseł. W przypadkach bardziej zaawansowanych chorób przyzębia, konieczne może być leczenie chirurgiczne lub ekstrakcja zębów. Oprócz zabiegów, stomatologia weterynaryjna obejmuje również doradztwo w zakresie profilaktyki, w tym regularnego szczotkowania zębów zwierzęcia, stosowania odpowiednich karm i przysmaków dentystycznych, które pomagają utrzymać zęby i dziąsła w dobrym stanie. Regularne kontrole stomatologiczne są kluczowe, aby zapobiegać rozwojowi chorób jamy ustnej, które mogą wpływać na ogólny stan zdrowia zwierzęcia. Stomatologia weterynaryjna odgrywa ważną rolę w zapewnieniu zwierzętom zdrowego i komfortowego życia. Odpowiednia opieka stomatologiczna nie tylko zapobiega bólowi i dyskomfortowi związanym z problemami zębów i dziąseł, ale także chroni przed poważniejszymi schorzeniami, które mogą wyniknąć z zaniedbania jamy ustnej. Dzięki regularnej profilaktyce i leczeniu, zwierzęta mogą cieszyć się zdrowymi zębami i lepszą jakością życia.',
                'price' => 75,
            ],
            [
                'name' => 'RTG',
                'slug' => 'rtg',
                'description' => '<strong>"RTG"</strong>, czyli radiografia, to jedno z podstawowych narzędzi diagnostycznych stosowanych do obrazowania wewnętrznych struktur ciała zwierząt. Badanie to pozwala na uzyskanie szczegółowych obrazów kości, stawów, narządów wewnętrznych, a także tkanek miękkich, co jest kluczowe w diagnozowaniu wielu schorzeń i urazów. RTG jest szczególnie przydatne w przypadkach złamań kości, wykrywania zmian nowotworowych, diagnozowania chorób płuc, serca, oraz w ocenie stanu narządów jamy brzusznej. Proces wykonywania zdjęcia rentgenowskiego w weterynarii rozpoczyna się od odpowiedniego przygotowania zwierzęcia. W niektórych przypadkach, zwłaszcza gdy wymagane jest uzyskanie szczegółowych obrazów, może być konieczne zastosowanie łagodnego znieczulenia, aby zapewnić, że zwierzę pozostanie nieruchome podczas badania. Samo badanie jest szybkie i bezbolesne, a obrazy uzyskane z RTG są natychmiast dostępne do analizy. Weterynarz, na podstawie tych obrazów, może dokładnie ocenić stan zdrowia zwierzęcia, wykryć ewentualne nieprawidłowości oraz zaplanować dalsze leczenie. RTG w weterynarii odgrywa kluczową rolę w diagnostyce i monitorowaniu postępów leczenia, szczególnie w przypadkach wymagających obserwacji zmian w strukturach wewnętrznych. Dzięki temu badaniu możliwe jest szybkie postawienie trafnej diagnozy i podjęcie odpowiednich działań, co znacząco zwiększa szanse na skuteczne leczenie. Radiografia jest również wykorzystywana w rutynowych badaniach kontrolnych, zwłaszcza u zwierząt starszych, gdzie pozwala na wczesne wykrycie problemów zdrowotnych, zanim staną się poważne. W kontekście opieki weterynaryjnej, RTG jest niezastąpionym narzędziem, które umożliwia dokładne i bezinwazyjne badanie, pomagając weterynarzom w podejmowaniu decyzji dotyczących leczenia, a tym samym w zapewnieniu zwierzętom najlepszej możliwej opieki.',
                'price' => 105,
            ],
            [
                'name' => 'USG',
                'slug' => 'usg',
                'description' => '<strong>"USG"</strong>, czyli ultrasonografia, to nieinwazyjna technika diagnostyczna, która wykorzystuje fale dźwiękowe do tworzenia obrazów wnętrza ciała zwierząt. Jest to niezwykle wszechstronne narzędzie, umożliwiające ocenę stanu narządów wewnętrznych, takich jak serce, wątroba, nerki, śledziona, pęcherz moczowy, a także tkanek miękkich i naczyń krwionośnych. USG jest szczególnie przydatne w diagnozowaniu chorób układu pokarmowego, układu moczowego, wątroby, a także w monitorowaniu ciąży i ocenie zdrowia płodów. Przeprowadzenie badania USG rozpoczyna się od nałożenia specjalnego żelu na skórę zwierzęcia, który ułatwia przewodzenie fal dźwiękowych. Weterynarz następnie przesuwa sondę ultrasonograficzną po badanym obszarze, co pozwala na uzyskanie dynamicznych, rzeczywistych obrazów narządów wewnętrznych na ekranie monitora. Badanie to jest bezbolesne i zazwyczaj nie wymaga znieczulenia, chociaż w niektórych przypadkach, zwłaszcza gdy zwierzę jest bardzo zestresowane, może być potrzebne lekkie uspokojenie. USG pozwala na dokładną ocenę struktury i funkcji narządów, wykrywanie zmian patologicznych, takich jak guzy, torbiele, kamienie nerkowe, a także na ocenę przepływu krwi w naczyniach. Dzięki swojej precyzji i możliwości uzyskania obrazów w czasie rzeczywistym, ultrasonografia jest niezwykle cenna w diagnozowaniu i monitorowaniu przebiegu leczenia wielu chorób. Ponadto, USG jest często stosowane jako metoda uzupełniająca inne badania diagnostyczne, takie jak RTG czy badania laboratoryjne, co pozwala na uzyskanie pełniejszego obrazu stanu zdrowia zwierzęcia. W weterynarii USG jest nieocenionym narzędziem, które wspomaga weterynarzy w szybkiej i precyzyjnej diagnostyce, a także w monitorowaniu postępów leczenia. Dzięki tej technologii możliwe jest wczesne wykrycie wielu schorzeń, co zwiększa szanse na skuteczne leczenie i poprawia jakość życia zwierząt.',
                'price' => 112,
            ],
            [
                'name' => 'Badania laboratoryjne',
                'slug' => 'badania-laboratoryjne',
                'description' => '<strong>"Badania laboratoryjne"</strong> to istotny element diagnostyki, który umożliwia szczegółową ocenę stanu zdrowia zwierząt na poziomie biochemicznym, hematologicznym i mikrobiologicznym. Dzięki nim weterynarze mogą wykrywać i monitorować różnorodne schorzenia, od infekcji, przez choroby metaboliczne, po zaburzenia funkcji narządów wewnętrznych. Badania laboratoryjne obejmują szeroki zakres testów, takich jak analiza krwi, moczu, kału, badania hormonalne, testy serologiczne, a także badania cytologiczne i mikrobiologiczne. Proces diagnostyczny z wykorzystaniem badań laboratoryjnych rozpoczyna się od pobrania odpowiednich próbek, takich jak krew, mocz czy wymazy, które następnie są poddawane szczegółowej analizie w laboratorium weterynaryjnym. W zależności od rodzaju testu, wyniki mogą dostarczyć informacji na temat ogólnego stanu zdrowia zwierzęcia, funkcjonowania narządów, takich jak wątroba, nerki czy trzustka, a także wykryć obecność infekcji bakteryjnych, wirusowych czy pasożytniczych. Na przykład, morfologia krwi pozwala na ocenę liczby i rodzaju komórek krwi, co jest kluczowe w diagnozowaniu anemii, infekcji czy stanów zapalnych, natomiast analiza biochemiczna krwi dostarcza informacji na temat metabolizmu i stanu narządów wewnętrznych. Badania laboratoryjne są również niezbędne w monitorowaniu postępów leczenia oraz w ocenie skuteczności zastosowanych terapii. Na przykład, regularne badania krwi mogą pomóc w monitorowaniu funkcji nerek u zwierzęcia z przewlekłą niewydolnością nerek, a badania moczu mogą wykrywać wczesne oznaki infekcji dróg moczowych lub kamieni nerkowych. Ponadto, badania laboratoryjne odgrywają kluczową rolę w prewencji, pozwalając na wczesne wykrycie problemów zdrowotnych u zwierząt w rutynowych badaniach kontrolnych. W weterynarii badania laboratoryjne są nieodzownym narzędziem, które wspiera weterynarzy w podejmowaniu trafnych decyzji diagnostycznych i terapeutycznych. Dzięki nim możliwe jest uzyskanie precyzyjnych informacji o stanie zdrowia zwierząt, co pozwala na skuteczniejsze leczenie, szybsze postawienie diagnozy i lepsze monitorowanie stanu zdrowia pacjentów, co w efekcie przyczynia się do poprawy jakości i długości życia zwierząt.',
                'price' => 140,
            ],
            [
                'name' => 'Szczepienia ochronne',
                'slug' => 'szczepienia-ochronne',
                'description' => '<strong>"Szczepienia ochronne"</strong> to kluczowy element profilaktyki zdrowotnej, mający na celu ochronę zwierząt przed poważnymi chorobami zakaźnymi. Szczepienia stymulują układ odpornościowy zwierzęcia do wytwarzania przeciwciał, które w przyszłości pomogą w zwalczaniu patogenów, takich jak wirusy czy bakterie. Regularne podawanie szczepionek jest niezwykle ważne zarówno dla zwierząt domowych, takich jak psy i koty, jak i dla zwierząt gospodarskich, gdzie odgrywa istotną rolę w utrzymaniu zdrowia całego stada. Proces szczepienia rozpoczyna się od konsultacji z weterynarzem, który na podstawie wieku, stanu zdrowia i stylu życia zwierzęcia, dobiera odpowiedni program szczepień. Najczęściej stosowane szczepionki obejmują te przeciwko takim chorobom jak wścieklizna, nosówka, parwowiroza, leptospiroza, zakaźne zapalenie wątroby, panleukopenia, koci katar, a także chorobom odzwierzęcym, które mogą stanowić zagrożenie dla ludzi. Pierwsze szczepienia zazwyczaj podaje się już w wieku szczenięcym lub kocięcym, a następnie, w zależności od rodzaju szczepionki, przeprowadza się regularne szczepienia przypominające. Szczepienia ochronne odgrywają nie tylko rolę w ochronie indywidualnego zwierzęcia, ale także w zapobieganiu rozprzestrzenianiu się chorób w populacji zwierząt. Dzięki szeroko zakrojonym programom szczepień, wiele groźnych chorób, które wcześniej były powszechne, jest obecnie rzadko spotykanych. Przykładem może być wścieklizna, która dzięki regularnym szczepieniom u zwierząt domowych i dzikich, została znacząco zredukowana w wielu regionach. W weterynarii szczepienia ochronne są fundamentalnym elementem dbałości o zdrowie zwierząt. Pozwalają one na zapobieganie ciężkim chorobom, zmniejszenie ryzyka epidemii i ochronę zdrowia publicznego. Regularne szczepienia zgodnie z zaleceniami weterynarza to najlepszy sposób, aby zapewnić zwierzętom długie, zdrowe i wolne od poważnych chorób życie.',
                'price' => 45,
            ],
            [
                'name' => 'Rozród i położnictwo',
                'slug' => 'rozrod-i-poloznictwo',
                'description' => '<strong>"Rozród i położnictwo"</strong> w weterynarii to specjalizacja zajmująca się opieką nad zwierzętami w kontekście rozmnażania, ciąży oraz porodu. Obejmuje szeroki zakres działań, od planowania i monitorowania cykli rozrodczych, przez diagnostykę i zarządzanie ciążą, aż po pomoc przy porodzie i opiekę nad nowonarodzonymi młodymi. W kontekście rozrodu, weterynarze zajmują się zarówno sztucznym inseminowaniem, jak i naturalnym rozmnażaniem zwierząt. Monitorują cykle rujowe samic, co pozwala na precyzyjne planowanie krycia, oraz stosują techniki wspomagające, takie jak hormonalne terapie, które mogą poprawić płodność. Diagnostyka płodności obejmuje badania ultrasonograficzne i hormonalne, które pomagają w ocenie stanu zdrowia układu rozrodczego oraz identyfikacji potencjalnych problemów, które mogą wpływać na zdolność do rozmnażania. Po wykryciu ciąży, weterynarz monitoruje jej przebieg, przeprowadzając regularne badania kontrolne, takie jak ultrasonografia, aby ocenić rozwój płodów i zdrowie matki. W przypadku problemów zdrowotnych, takich jak zagrożenie poronieniem, infekcje czy niedobory żywieniowe, podejmowane są odpowiednie środki zaradcze, aby zapewnić zdrowie matki i potomstwa. Dodatkowo, w trakcie ciąży doradza się właścicielom zwierząt na temat właściwej diety, przygotowania miejsca do porodu i monitorowania objawów, które mogą sugerować problemy. Pomoc przy porodzie, czyli położnictwo, to kluczowy moment, który wymaga szczególnej uwagi i umiejętności. Weterynarz może pomóc w przypadku komplikacji podczas porodu, takich jak dystocja (trudny poród) czy niewłaściwe ułożenie płodów. W przypadku potrzeby przeprowadzenia cesarskiego cięcia, weterynarz wykonuje operację, aby bezpiecznie wydobyć młode. Po porodzie, opieka położnicza obejmuje monitorowanie zdrowia matki i młodych, zapewnienie prawidłowego karmienia oraz identyfikację ewentualnych problemów zdrowotnych. W zakresie "rozrodu i położnictwa" weterynaria odgrywa kluczową rolę w zapewnieniu zdrowego przebiegu cyklu rozrodczego, ciąży i porodu. Dzięki specjalistycznej opiece, możliwe jest nie tylko zwiększenie efektywności rozmnażania, ale także zapewnienie bezpieczeństwa i zdrowia zarówno matce, jak i nowonarodzonym młodym.',
                'price' => 90,
            ],
            [
                'name' => 'Chirurgia ogólna',
                'slug' => 'chirurgia-ogolna',
                'description' => '<strong>"Chirurgia ogólna"</strong> to dziedzina zajmująca się diagnozowaniem i leczeniem chirurgicznym szerokiego zakresu schorzeń u zwierząt, obejmująca zarówno rutynowe, jak i skomplikowane zabiegi operacyjne. Chirurgia ogólna jest podstawowym filarem opieki weterynaryjnej, która pozwala na skuteczne leczenie urazów, chorób i problemów zdrowotnych wymagających interwencji chirurgicznej. Proces chirurgii ogólnej rozpoczyna się od dokładnej diagnostyki, która może obejmować badania fizykalne, diagnostykę obrazową (taką jak RTG, USG), oraz badania laboratoryjne, aby dokładnie ocenić stan zdrowia zwierzęcia i określić zakres koniecznej operacji. Weterynarz przygotowuje plan chirurgiczny, który uwzględnia specyfikę schorzenia oraz ogólny stan zdrowia pacjenta. Przed przystąpieniem do zabiegu, zwierzę jest odpowiednio przygotowywane, co może obejmować przygotowanie pola operacyjnego, wprowadzenie zwierzęcia w znieczulenie ogólne oraz monitorowanie jego parametrów życiowych. W ramach chirurgii ogólnej wykonywane są różnorodne zabiegi, takie jak usuwanie guzów, naprawa złamań kości, operacje na narządach wewnętrznych, takich jak żołądek, jelita, wątroba czy pęcherz moczowy. Chirurgia ogólna obejmuje również procedury związane z układem rozrodczym, takie jak sterylizacja i kastracja, oraz leczenie ran, które nie goją się samodzielnie. Każdy zabieg wymaga precyzyjnego podejścia i techniki chirurgicznej, aby zapewnić jak najlepsze rezultaty i minimalizować ryzyko powikłań. Po operacji, opieka pooperacyjna jest kluczowa dla prawidłowego powrotu zwierzęcia do zdrowia. Weterynarz monitoruje stan pacjenta, zapewnia odpowiednie leki przeciwbólowe i antybiotyki, oraz instruuje właściciela zwierzęcia w zakresie opieki domowej, takiej jak zmiana opatrunków, kontrolowanie ran oraz obserwowanie objawów mogących wskazywać na powikłania. Regularne wizyty kontrolne mogą być konieczne, aby ocenić postępy w leczeniu i dokonać ewentualnych korekt w planie opieki. Chirurgia ogólna w weterynarii odgrywa fundamentalną rolę w leczeniu wielu schorzeń i urazów, pozwalając na poprawę jakości życia zwierząt oraz przywrócenie ich zdrowia i sprawności. Dzięki zaawansowanej technologii i umiejętnościom chirurgicznym weterynarzy, możliwe jest skuteczne leczenie wielu poważnych stanów zdrowotnych, co przyczynia się do długowieczności i dobrego samopoczucia pacjentów.',
                'price' => 150,
            ],
        ];

        foreach ($services as $key => $value)
        {
            Service::create($value);
        }
    }
}
